name: Auto Create Pull Request

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

  workflow_dispatch:  # Allows manual execution

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create a New Branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git checkout -b feature-branch
          echo "This is a test PR" > test-file.txt
          git add test-file.txt
          git commit -m "Automated scaffold update"

      - name: Push Branch
        run: |
          git push origin feature-branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: feature-branch
          base: main
          title: "Automated PR: Test File Addition"
          body: "This PR was created automatically using GitHub Actions."
          token: ${{ secrets.GITHUB_TOKEN }}
